% ============================================================
% Feasibility scoring rules for synthesized VLSI SWSC paths
%
% These rules classify paths generated by the core Prolog model.
%
% Core model:
%   attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome)
%
% Feasibility labels:
%   high_feasibility_path(...)
%   medium_feasibility_path(...)
%   low_feasibility_path(...)
% ============================================================

% -----------------------------
% Helper predicates
% -----------------------------

supported(Level) :-
    Level = high;
    Level = medium.

category_supported(Layer, Category) :-
    category_feasibility(Layer, Category, Level),
    supported(Level).

category_high(Layer, Category) :-
    category_feasibility(Layer, Category, high).

% -----------------------------
% High feasibility
%
% High means all main parts have evidence:
%   A_sw   = high
%   M_sw   = high
%   A_vlsi = medium or high
%   Stage  = observed in v1 evidence
% -----------------------------

high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome) :-
    attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    category_high(asw, A_sw),
    category_high(msw, M_sw),
    category_supported(avlsi, A_vlsi),
    observed_stage(Stage).

% -----------------------------
% Medium feasibility
%
% Medium means the path has some evidence support, but it does
% not satisfy all High conditions.
% -----------------------------

medium_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome) :-
    attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    \+ high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    once((
        (category_supported(asw, A_sw), category_supported(msw, M_sw));
        (category_high(asw, A_sw), observed_stage(Stage));
        (category_high(msw, M_sw), observed_stage(Stage));
        (
            category_supported(avlsi, A_vlsi),
            observed_stage(Stage),
            (
                category_supported(asw, A_sw);
                category_supported(msw, M_sw)
            )
        )
    )).

% -----------------------------
% Low feasibility
%
% Low means the path is possible in the model, but current v1
% evidence does not support it enough for High or Medium.
% -----------------------------

low_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome) :-
    attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    \+ high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    \+ medium_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome).

% -----------------------------
% Counts
% -----------------------------

count_high_feasibility_paths(N) :-
    aggregate_all(
        count,
        distinct((A_sw, M_sw, A_vlsi, Stage, Outcome),
                 high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome)),
        N
    ).

count_medium_feasibility_paths(N) :-
    aggregate_all(
        count,
        distinct((A_sw, M_sw, A_vlsi, Stage, Outcome),
                 medium_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome)),
        N
    ).

count_low_feasibility_paths(N) :-
    aggregate_all(
        count,
        distinct((A_sw, M_sw, A_vlsi, Stage, Outcome),
                 low_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome)),
        N
    ).

count_all_feasibility_paths(Total) :-
    count_high_feasibility_paths(H),
    count_medium_feasibility_paths(M),
    count_low_feasibility_paths(L),
    Total is H + M + L.
