% ============================================================
% Feasibility scoring rules for synthesized VLSI SWSC paths
%
% These rules classify paths generated by the core Prolog model.
%
% Core model:
%   attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome)
%
% Feasibility labels:
%   high_feasibility_path(...)
%   medium_feasibility_path(...)
%   low_feasibility_path(...)
% ============================================================

% -----------------------------
% Helper predicates
% -----------------------------

supported(Level) :-
    Level = high;
    Level = medium.

category_supported(Layer, Category) :-
    category_feasibility(Layer, Category, Level),
    supported(Level).

category_high(Layer, Category) :-
    category_feasibility(Layer, Category, high).

% -----------------------------
% Evidence trace helpers
%
% These helpers connect feasibility labels back to E1-E50
% through the evidence_mapping facts.
% -----------------------------

category_evidence_ids(Layer, Category, EvidenceIDs) :-
    findall(EvidenceID,
            evidence_supports_category(EvidenceID, Layer, Category, _),
            IDs),
    sort(IDs, EvidenceIDs).

category_has_evidence(Layer, Category) :-
    evidence_supports_category(_, Layer, Category, _).

category_high_with_evidence(Layer, Category) :-
    category_high(Layer, Category),
    category_has_evidence(Layer, Category).

category_supported_with_evidence(Layer, Category) :-
    category_supported(Layer, Category),
    category_has_evidence(Layer, Category).


% -----------------------------
% High feasibility
%
% High means all main parts have evidence:
%   A_sw   = high
%   M_sw   = high
%   A_vlsi = medium or high
%   Stage  = observed in v1 evidence
% -----------------------------

high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome) :-
    attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    category_high_with_evidence(asw, A_sw),
    category_high_with_evidence(msw, M_sw),
    category_supported_with_evidence(avlsi, A_vlsi),
    observed_stage(Stage).

% -----------------------------
% Medium feasibility
%
% Medium means the path has some evidence support, but it does
% not satisfy all High conditions.
% -----------------------------

medium_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome) :-
    attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    \+ high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    once((
        (category_supported(asw, A_sw), category_supported(msw, M_sw));
        (category_high(asw, A_sw), observed_stage(Stage));
        (category_high(msw, M_sw), observed_stage(Stage));
        (
            category_supported(avlsi, A_vlsi),
            observed_stage(Stage),
            (
                category_supported(asw, A_sw);
                category_supported(msw, M_sw)
            )
        )
    )).

% -----------------------------
% Low feasibility
%
% Low means the path is possible in the model, but current v1
% evidence does not support it enough for High or Medium.
% -----------------------------

low_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome) :-
    attack_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    \+ high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    \+ medium_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome).

% -----------------------------
% Counts
% -----------------------------

count_high_feasibility_paths(N) :-
    aggregate_all(
        count,
        distinct((A_sw, M_sw, A_vlsi, Stage, Outcome),
                 high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome)),
        N
    ).

count_medium_feasibility_paths(N) :-
    aggregate_all(
        count,
        distinct((A_sw, M_sw, A_vlsi, Stage, Outcome),
                 medium_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome)),
        N
    ).

count_low_feasibility_paths(N) :-
    aggregate_all(
        count,
        distinct((A_sw, M_sw, A_vlsi, Stage, Outcome),
                 low_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome)),
        N
    ).

count_all_feasibility_paths(Total) :-
    count_high_feasibility_paths(H),
    count_medium_feasibility_paths(M),
    count_low_feasibility_paths(L),
    Total is H + M + L.

% -----------------------------
% Path trace with evidence IDs
% -----------------------------

high_feasibility_path_with_evidence(
    A_sw, M_sw, A_vlsi, Stage, Outcome,
    A_sw_EvidenceIDs, M_sw_EvidenceIDs, A_vlsi_EvidenceIDs
) :-
    high_feasibility_path(A_sw, M_sw, A_vlsi, Stage, Outcome),
    category_evidence_ids(asw, A_sw, A_sw_EvidenceIDs),
    category_evidence_ids(msw, M_sw, M_sw_EvidenceIDs),
    category_evidence_ids(avlsi, A_vlsi, A_vlsi_EvidenceIDs).
