% Auto-generated from data/Asw/asw_mechanism_mapping_prolog_ready.csv
% ASW-side facts: A_sw -> M

% SWSC attack vectors
swsc_vector(abuse_dependency_resolution_mechanism).
swsc_vector(account_takeover).
swsc_vector(altering_word_order).
swsc_vector(become_a_maintainer).
swsc_vector(brandjacking).
swsc_vector(bribe_or_blackmail_legitimate_user).
swsc_vector(bruteforce).
swsc_vector(built_in_package).
swsc_vector(case_sensitivity_confusion).
swsc_vector(certificate_theft).
swsc_vector(code_injection).
swsc_vector(combosquatting).
swsc_vector(commit_as_maintainer).
swsc_vector(compromise_build_system).
swsc_vector(compromise_hosting_system).
swsc_vector(compromise_maintainer_system).
swsc_vector(compromise_user_project_maintainer_administrator).
swsc_vector(compromise_version_control_system).
swsc_vector(compromised_tools).
swsc_vector(contribute_as_maintainer).
swsc_vector(create_name_confusion_with_legitimate_package).
swsc_vector(create_new_package).
swsc_vector(credential_stuffing).
swsc_vector(dangling_reference).
swsc_vector(dependency_confusion).
swsc_vector(dependency_confusion_attack).
swsc_vector(deploy_in_alternative_repository_or_mirror).
swsc_vector(develop_and_advertise_distinct_malicious_package).
swsc_vector(distribute_as_package_maintainer).
swsc_vector(distribute_malicious_version_of_legitimate_package).
swsc_vector(dns_cache_poisoning).
swsc_vector(exploit_rendering_weakness).
swsc_vector(exploit_unicode_bidirectional_algorithm).
swsc_vector(exploit_vulnerabilities).
swsc_vector(exploit_weak_configuration).
swsc_vector(exploitation_of_signature_system).
swsc_vector(exploiting_unmaintained_legacy_code).
swsc_vector(ghost_package_attack_in_mirrors).
swsc_vector(hide_in_generated_compiled_minified_code).
swsc_vector(infect_existing_package).
swsc_vector(infect_through_malicious_component).
swsc_vector(inject_during_build_of_legitimate_package).
swsc_vector(inject_during_the_build).
swsc_vector(inject_into_hosting_system).
swsc_vector(inject_into_repository_system).
swsc_vector(inject_into_source).
swsc_vector(inject_into_sources_of_legitimate_package).
swsc_vector(introduce_malicious_code_through_hypocrite_merge_request).
swsc_vector(make_immature_vulnerability_exploitable).
swsc_vector(manipulate_package_download).
swsc_vector(manipulating_word_separators).
swsc_vector(mask_legitimate_package).
swsc_vector(mirror_package_override).
swsc_vector(misconfigurations).
swsc_vector(mitm_attack).
swsc_vector(ownership_transfer).
swsc_vector(package_maintainer_account_hijacking).
swsc_vector(package_redirection_hijacking).
swsc_vector(package_reference_attack).
swsc_vector(package_tampering_attack).
swsc_vector(package_use_after_free).
swsc_vector(package_version_downgrade).
swsc_vector(package_version_downgrade_attack).
swsc_vector(package_version_reuse).
swsc_vector(package_version_reuse_attack).
swsc_vector(phishing).
swsc_vector(prevent_display_of_file_differences).
swsc_vector(prevent_update_to_non_vulnerable_version).
swsc_vector(pull_request_as_contributor).
swsc_vector(resurrect_expired_domain_associated_with_legitimate_account).
swsc_vector(reuse_of_compromised_credentials).
swsc_vector(reuse_of_existing_session).
swsc_vector(reuse_of_leaked_api_tokens).
swsc_vector(run_malicious_build).
swsc_vector(run_malicious_build_on_shared_systems).
swsc_vector(similarity_attack).
swsc_vector(social_engineering_to_become_maintainer).
swsc_vector(social_engineering_to_obtain_credentials).
swsc_vector(subvert_legitimate_package).
swsc_vector(take_over_legitimate_account).
swsc_vector(tamper_build_job_as_maintainer).
swsc_vector(tamper_legitimate_url).
swsc_vector(tamper_with_exposed_build_system).
swsc_vector(tamper_with_version_control_system).
swsc_vector(trojan_horse_package).
swsc_vector(typosquatting).
swsc_vector(typosquatting_and_combosquatting).
swsc_vector(typosquatting_in_registries).
swsc_vector(use_after_free).
swsc_vector(use_homoglyphs).
swsc_vector(weak_or_compromised_credentials_or_api_tokens).

% SWSC-enabled mechanisms
mechanism(abused_legitimate_user_privileges).
mechanism(attacker_controlled_build_artifact).
mechanism(attacker_controlled_build_execution).
mechanism(attacker_controlled_build_system).
mechanism(attacker_controlled_dependency_reference).
mechanism(attacker_controlled_dependency_resolution).
mechanism(attacker_controlled_development_tool).
mechanism(attacker_controlled_distribution_channel).
mechanism(attacker_controlled_distribution_reference).
mechanism(attacker_controlled_hidden_source_change).
mechanism(attacker_controlled_hosting_system).
mechanism(attacker_controlled_insecure_development_configuration).
mechanism(attacker_controlled_legitimate_software_artifact).
mechanism(attacker_controlled_lookalike_software_artifact).
mechanism(attacker_controlled_malicious_software_artifact).
mechanism(attacker_controlled_mirror_resolution).
mechanism(attacker_controlled_package_content_tampering).
mechanism(attacker_controlled_package_name_resolution).
mechanism(attacker_controlled_released_artifact).
mechanism(attacker_controlled_reused_package_name).
mechanism(attacker_controlled_reused_version_artifact).
mechanism(attacker_controlled_signature_verification_bypass).
mechanism(attacker_controlled_signing_identity).
mechanism(attacker_controlled_source_code).
mechanism(attacker_controlled_stale_mirror_artifact).
mechanism(attacker_controlled_update_path).
mechanism(attacker_controlled_version_control_system).
mechanism(attacker_exploitable_vulnerable_dependency).
mechanism(compromised_legitimate_account_control).
mechanism(compromised_maintainer_system_control).
mechanism(compromised_project_user_privileges).
mechanism(maintainer_level_build_job_control).
mechanism(maintainer_level_release_control).
mechanism(maintainer_level_source_control).

% A_sw enables M
enables(abuse_dependency_resolution_mechanism, attacker_controlled_dependency_resolution).
enables(account_takeover, compromised_legitimate_account_control).
enables(altering_word_order, attacker_controlled_lookalike_software_artifact).
enables(become_a_maintainer, maintainer_level_build_job_control).
enables(become_a_maintainer, maintainer_level_release_control).
enables(become_a_maintainer, maintainer_level_source_control).
enables(brandjacking, attacker_controlled_lookalike_software_artifact).
enables(bribe_or_blackmail_legitimate_user, abused_legitimate_user_privileges).
enables(bruteforce, compromised_legitimate_account_control).
enables(built_in_package, attacker_controlled_lookalike_software_artifact).
enables(case_sensitivity_confusion, attacker_controlled_package_name_resolution).
enables(certificate_theft, attacker_controlled_signing_identity).
enables(code_injection, attacker_controlled_source_code).
enables(combosquatting, attacker_controlled_lookalike_software_artifact).
enables(commit_as_maintainer, maintainer_level_source_control).
enables(compromise_build_system, attacker_controlled_build_system).
enables(compromise_hosting_system, attacker_controlled_hosting_system).
enables(compromise_maintainer_system, compromised_maintainer_system_control).
enables(compromise_user_project_maintainer_administrator, compromised_project_user_privileges).
enables(compromise_version_control_system, attacker_controlled_version_control_system).
enables(compromised_tools, attacker_controlled_development_tool).
enables(contribute_as_maintainer, maintainer_level_source_control).
enables(create_name_confusion_with_legitimate_package, attacker_controlled_lookalike_software_artifact).
enables(create_new_package, attacker_controlled_malicious_software_artifact).
enables(credential_stuffing, compromised_legitimate_account_control).
enables(dangling_reference, attacker_controlled_distribution_reference).
enables(dependency_confusion, attacker_controlled_dependency_resolution).
enables(dependency_confusion_attack, attacker_controlled_dependency_resolution).
enables(deploy_in_alternative_repository_or_mirror, attacker_controlled_distribution_reference).
enables(develop_and_advertise_distinct_malicious_package, attacker_controlled_malicious_software_artifact).
enables(distribute_as_package_maintainer, maintainer_level_release_control).
enables(distribute_malicious_version_of_legitimate_package, attacker_controlled_released_artifact).
enables(dns_cache_poisoning, attacker_controlled_distribution_channel).
enables(exploit_rendering_weakness, attacker_controlled_hidden_source_change).
enables(exploit_unicode_bidirectional_algorithm, attacker_controlled_hidden_source_change).
enables(exploit_vulnerabilities, attacker_controlled_hosting_system).
enables(exploit_vulnerabilities, compromised_maintainer_system_control).
enables(exploit_weak_configuration, compromised_maintainer_system_control).
enables(exploitation_of_signature_system, attacker_controlled_signature_verification_bypass).
enables(exploiting_unmaintained_legacy_code, attacker_exploitable_vulnerable_dependency).
enables(ghost_package_attack_in_mirrors, attacker_controlled_stale_mirror_artifact).
enables(hide_in_generated_compiled_minified_code, attacker_controlled_hidden_source_change).
enables(infect_existing_package, attacker_controlled_legitimate_software_artifact).
enables(infect_through_malicious_component, compromised_maintainer_system_control).
enables(inject_during_build_of_legitimate_package, attacker_controlled_build_artifact).
enables(inject_during_the_build, attacker_controlled_build_artifact).
enables(inject_into_hosting_system, attacker_controlled_hosting_system).
enables(inject_into_repository_system, attacker_controlled_hosting_system).
enables(inject_into_source, attacker_controlled_source_code).
enables(inject_into_sources_of_legitimate_package, attacker_controlled_source_code).
enables(introduce_malicious_code_through_hypocrite_merge_request, attacker_controlled_source_code).
enables(make_immature_vulnerability_exploitable, attacker_controlled_source_code).
enables(manipulate_package_download, attacker_controlled_distribution_channel).
enables(manipulating_word_separators, attacker_controlled_lookalike_software_artifact).
enables(mask_legitimate_package, attacker_controlled_released_artifact).
enables(mirror_package_override, attacker_controlled_mirror_resolution).
enables(misconfigurations, attacker_controlled_insecure_development_configuration).
enables(mitm_attack, attacker_controlled_distribution_channel).
enables(ownership_transfer, maintainer_level_release_control).
enables(package_maintainer_account_hijacking, compromised_legitimate_account_control).
enables(package_redirection_hijacking, attacker_controlled_distribution_reference).
enables(package_reference_attack, attacker_controlled_dependency_reference).
enables(package_tampering_attack, attacker_controlled_package_content_tampering).
enables(package_use_after_free, attacker_controlled_reused_package_name).
enables(package_version_downgrade, attacker_controlled_update_path).
enables(package_version_downgrade_attack, attacker_controlled_update_path).
enables(package_version_reuse, attacker_controlled_reused_version_artifact).
enables(package_version_reuse_attack, attacker_controlled_reused_version_artifact).
enables(phishing, compromised_legitimate_account_control).
enables(prevent_display_of_file_differences, attacker_controlled_hidden_source_change).
enables(prevent_update_to_non_vulnerable_version, attacker_controlled_update_path).
enables(pull_request_as_contributor, attacker_controlled_source_code).
enables(resurrect_expired_domain_associated_with_legitimate_account, compromised_legitimate_account_control).
enables(reuse_of_compromised_credentials, compromised_legitimate_account_control).
enables(reuse_of_existing_session, compromised_legitimate_account_control).
enables(reuse_of_leaked_api_tokens, compromised_legitimate_account_control).
enables(run_malicious_build, attacker_controlled_build_execution).
enables(run_malicious_build_on_shared_systems, attacker_controlled_build_execution).
enables(similarity_attack, attacker_controlled_lookalike_software_artifact).
enables(social_engineering_to_become_maintainer, maintainer_level_source_control).
enables(social_engineering_to_obtain_credentials, compromised_legitimate_account_control).
enables(subvert_legitimate_package, attacker_controlled_legitimate_software_artifact).
enables(take_over_legitimate_account, compromised_legitimate_account_control).
enables(tamper_build_job_as_maintainer, maintainer_level_build_job_control).
enables(tamper_legitimate_url, attacker_controlled_distribution_reference).
enables(tamper_with_exposed_build_system, attacker_controlled_build_system).
enables(tamper_with_version_control_system, attacker_controlled_version_control_system).
enables(trojan_horse_package, attacker_controlled_malicious_software_artifact).
enables(typosquatting, attacker_controlled_lookalike_software_artifact).
enables(typosquatting_and_combosquatting, attacker_controlled_lookalike_software_artifact).
enables(typosquatting_in_registries, attacker_controlled_lookalike_software_artifact).
enables(use_after_free, attacker_controlled_distribution_reference).
enables(use_homoglyphs, attacker_controlled_hidden_source_change).
enables(weak_or_compromised_credentials_or_api_tokens, compromised_legitimate_account_control).
